import "./globals.css";
import Nav from "./auth/Nav";

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="mx-4 md:mx-48 xl:mx-96 bg-gray-200">
        <Nav />
        {children}
      </body>
    </html>
  );
}
